name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check JS syntax
        run: make check-js

      - name: Run AMO linter
        run: |
          npm install -g web-ext
          web-ext lint --self-hosted
